apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: randomquotes-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: randomquotes-test
  source:
    path: k8s/overlays/test
    repoURL: https://github.com/adamoctoclosegitops/RandomQuotes-K8s.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
