apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomquotes-deployment
  annotations:
    codefresh.io/product: randomquotes
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: randomquotes-web
  template:
    metadata:
      labels:
        component: randomquotes-web
    spec:
      containers:
        - name: randomquotes-k8s
          image: octopussamples/randomquotes-k8s:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: "Always"
          ports:
           - containerPort: 5000
             name: http-port
          env:
           - name: RANDOM_SECRET_PHRASE
             valueFrom:
               secretKeyRef:
                 name: random-quotes-secrets
                 key: homepageDisplay          
---
apiVersion: v1
kind: Service
metadata:
  name: randomquotes-app-cluster-ip-service  
spec:
  type: ClusterIP
  selector:
    component: randomquotes-web
  ports:
    - port: 6801
      targetPort: 8080
