apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: randomquotes-dev
resources:
- ../../base

secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="blah dev"

images:
 - name: randomquotes-k8s
   newName: octopussamples/randomquotes-k8s
   newTag: "0.1.6"
