name: Build and Push Multi-Arch Container

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: 5.x

      - name: Determine version with GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          additionalArguments: /overrideconfig mode=Mainline

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_PAT_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch Docker image
        working-directory: src
        run: |
          docker buildx build --push \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg TARGETARCH_ARG=true \
            -f ./RandomQuotes.Web/Dockerfile \
            -t ${{ secrets.DOCKERHUB_REPO }}:${{ steps.gitversion.outputs.semVer }} \
            -t ${{ secrets.DOCKERHUB_REPO }}:latest .

            
      - name: Report Image to Codefresh
        uses: codefresh-io/codefresh-report-image@latest
        with:
          CF_PLATFORM_URL: 'https://g.codefresh.io/'
          CF_RUNTIME_NAME: 'codefresh'
          CF_API_KEY: '${{ secrets.CF_API_KEY }}'
          CF_IMAGE: '${{ secrets.DOCKERHUB_REPO }}:${{ steps.gitversion.outputs.semVer }}'
          CF_DOCKERHUB_USERNAME: '${{ secrets.DOCKERHUB_PAT_USERNAME }}'
          CF_DOCKERHUB_PASSWORD: '${{ secrets.DOCKERHUB_PAT }}'
          CF_GIT_BRANCH: '${{ github.head_ref }}'
          CF_GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CF_JIRA_HOST_URL: 'https://adamclose.atlassian.net/'
          CF_JIRA_EMAIL: 'adam.close@octopus.com'
          CF_JIRA_API_TOKEN: 'secrets.JIRA_TOKEN'
          CF_JIRA_PROJECT_PREFIX: 'RAN'
          CF_JIRA_MESSAGE: '${{ github.event.pull_request.head.ref }}'
          CF_ENRICHERS: 'git, jira'
          CF_LOGS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          CF_WORKFLOW_NAME: ${{ github.workflow }}
          CF_WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
