name: Build and Push Container

on:
  push:
    branches: 
      - main
    paths:
      - 'src/**'
      - '.github/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: 5.x

      - name: Determine version with GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          additionalArguments: /overrideconfig mode=Mainline

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_PAT_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (amd64 only)
        working-directory: src
        run: |
          docker buildx build --push \
            --platform linux/amd64 \
            -f ./RandomQuotes.Web/Dockerfile \
            -t ${{ secrets.DOCKERHUB_REPO }}:${{ steps.gitversion.outputs.semVer }} \
            -t ${{ secrets.DOCKERHUB_REPO }}:latest .
