apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: randomquotes-staging
resources:
  - ../../base

secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="blah staging"

images:
  - name: adamoctoclose/randomquotes
    newName: adamoctoclose/randomquotes
    newTag: 0.1.139
