apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: randomquotes-staging
resources:
- ../../base

secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="blah staging"

images:
 - name: octopussamples/randomquotes-k8s
   newName: octopussamples/randomquotes-k8s
   newTag: "0.1.5"
